codimd_source: https://static.labcode.de/build/codimd/codimd-pandoc-1.6.0.tar.gz

codimd_db_database: "hackmd"
codimd_db_username: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/codimd/db subkey=user') }}"
codimd_db_password: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/codimd/db') }}"

codimd_session_secret: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/codimd subkey=session') }}"

codimd_allowed_origins:
  - "md.noemis.me"
  - "md.n0emis.eu"

codimd_allow_email_login: false
codimd_allow_email_register: false
codimd_allow_anonymous: false

codimd_domain: "md.n0emis.eu"
codimd_port: 3000
codimd_saml:
  issuer: "codimd"
  idpSSOUrl: "https://auth.n0emis.eu/auth/realms/n0emis/protocol/saml"
  idpCert: "MIICmzCCAYMCBgFx6qjSRDANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZuMGVtaXMwHhcNMjAwNTA2MTU0MjQ0WhcNMzAwNTA2MTU0NDI0WjARMQ8wDQYDVQQDDAZuMGVtaXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCpVEqmTR/KXCKPvWSoPcbx5QceUGoDWcFHKFnFbXnHsCTi3VuLduXgUveUZu9oaX6W9ALBkFLOFffAv9bzVaYq89k/OF6uVFBMSP4dmVM3vPTUnn+/dMdrybOEbo/Ujg49xXeip+LigcV9r1WrZTneX8EYnm7o4dY7PjMdi59AdawdQo0ngf51dsN38AQjcB6qQDi7fBx6S1mTNJuNko+jPW0RBjZKMRea9EFfnuZwTIqQqMGeIMYwSJK8uTr4BnNAfQmCF4mBBYzkTPGSSDirQZ2B6JxGMGP/7iC0iQRhFTxUdGth7qvNp4OtIzmyS1dvOn+paCA2Q8wXKTdrG6wtAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAIVH0wMqeT+jyFOlNtd93HGT/mgTNxITWX1MCf8ou3qCVfasqJRZ4T8DkMxl1smFe8BWFHyIMrgf7YPYe9jsDTGxvo1oLBbwsLiAjqmZPBVT1D4rGh0W/B7lQ6UsHc19lY57bV1K85ux/lurtl0kr1VJNkGByZqAvVcLyX4NakVGaQaZWA3TZbnLQJY7UcoOo3nFDsgnKFjtBmtQybyt58hTB2stEqn+tSuCRQHomfLkaYNa9mpwJi9Z7sv4hFHXibxQX6ev9/JCe0i3uAMm4WHAlpZ7QPGIeB/p5ZyYXcNoux7G5ju7q5T0431lYx3iWORAnSvyeGmqe7OLHgNpvmA="
  attributes:
    email: "email"
    username: "username"