---
keycloak_postgresql_username: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/keycloak/db subkey=user') }}"
keycloak_postgresql_password: "{{ lookup('passwordstore', 'infra/' + ansible_fqdn + '/keycloak/db') }}"
keycloak_postgresql_database: "keycloak"
keycloak_admin_password: "{{ lookup('passwordstore', 'auth.n0emis.eu/admin') }}"
keycloak_configure_firewall: false
keycloak_http_port: 8081
keycloak_welcome_theme: "n0emis-keycloak-theme"
keycloak_profile_preview: true

keycloak_version: 11.0.0-patched
keycloak_url: "https://home.noemis.me/tmp/keycloak-11.0.0-patched.zip"

#keycloak_java_opts: "-Xms512m -Xmx1024m -XX:MaxPermSize=768m"
