dns_dkim:   '3600   IN  TXT "v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwe4QWN7bOpSWpOcGo2jIjka7yixbe9D4Zft73vdX5n9OoO/Ozcs6dqzn0wrENPHw0R7u/L5sP/6HvNnfO/1ynGlRqqtUWRneE15CytZqFH0/X1PWHdC0bEAADyOYM3JzhVApum9wPBFuAjr4bOoESklC5um1nq8BlhtA+wKvHr8Fte9mC5Q1ax2seet/Et32q1aNrc20aU1X2viwPAK01kS8Oj/FpTp4HsDRO+NhmOapgBKWYvuJP8E9lQp+qDhPCs9orQ+l+wJuzkdjRyJn9/0R3a7mojWVIfSicfXEdSemc4bYojXCzyySIusFKnoXGtm2ZYnecc3FcHZnCHp7hwIDAQAB"'
dns_dmarc:  '3600	IN  TXT "v=DMARC1; p=quarantine; rua=mailto:mailauth-reports@n0emis.eu; ruf=mailto:mailauth-reports@n0emis.eu; fo=1"'
dns_mx:     '3600	IN  MX  1 ganymed.het.hel.fi.n0emis.eu.'
dns_spf:    '3600	IN	TXT "v=spf1 mx ~all"'
dns_tlsa:   'ganymed.het.hel.fi.n0emis.eu. 3600 IN TLSA 3 1 1 C9C26F6BBC3DE806274AF05FDCE17EB019A6C2FB7281BF5559F5DEDC C07683CB'

powerdns_config_directory: "/etc/powerdns"

pdns_install_repo: "{{ pdns_auth_powerdns_repo_44 }}"
pdns_config:
  master: yes
  expand-alias: yes
  loglevel: 10
  local-port: 53
  resolver: 1.1.1.1

pdns_backends:
  bind:
    config: "{{ powerdns_config_directory }}/named.conf"
    check-interval: 60

pdns_backends_packages:
  bind: pdns-backend-bind
  geo: pdns-backend-geo
  geoip: pdns-backend-geoip
  gmysql: pdns-backend-mysql
  gpgsql: pdns-backend-pgsql
  gsqlite3: pdns-backend-sqlite3
  ldap: pdns-backend-ldap
  lmdb: pdns-backend-lmdb
  lua: pdns-backend-lua
  mydns: pdns-backend-mydns
  pipe: pdns-backend-pipe
  remote: pdns-backend-remote
  tinydns: pdns-backend-tinydns

#pdns_rec_forward_dn42: "212.227.174.29;2001:8d8:1800:30e::1"
#pdns_rec_forward_cccgoe: "{{ pdns_rec_forward_dn42 }}"
#pdns_rec_forward_dyn: "78.46.251.132;2a01:4f8:c0c:34bc::1"
#
#pdns_rec_service_overrides: {}
#pdns_rec_config:
#  allow-from: "0.0.0.0/0, ::/0"
#  local-address: "0.0.0.0:53 [::]:53"
#  dont-query: "192.168.0.0/16, ::1/128, fe80::/10"
#  forward-zones:
#    - "n0emis.eu=127.0.0.1:5300"
#    - "dyn.n0emis.eu=127.0.0.1:5300"
#    - "noemis.me=127.0.0.1:5300"
#    - "n0emis.tk=127.0.0.1:5300"
#    - "n0emis.dn42=127.0.0.1:5300"
#
#    - "dn42={{ pdns_rec_forward_dn42 }}"
#    - "d.f.ip6.arpa={{ pdns_rec_forward_dn42 }}"
#    - "20.172.in-addr.arpa={{ pdns_rec_forward_dn42 }}"
#    - "21.172.in-addr.arpa={{ pdns_rec_forward_dn42 }}"
#    - "22.172.in-addr.arpa={{ pdns_rec_forward_dn42 }}"
#    - "23.172.in-addr.arpa={{ pdns_rec_forward_dn42 }}"
#
#    - "cccgoe={{ pdns_rec_forward_cccgoe }}"
#    - "7.9.0.d.f.7.e.7.8.f.d.f.ip6.arpa={{ pdns_rec_forward_cccgoe }}"

