http:
  routers:
    service-proxmox-http:
      rule: "Host(`kallisto.int.goe.de.n0emis.eu`)"
      service: "service-proxmox@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    service-proxmox-https:
      rule: "Host(`kallisto.int.goe.de.n0emis.eu`)"
      service: "service-proxmox@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "le_http"
  services:
    service-proxmox:
      loadBalancer:
        servers:
          - url: "https://kallisto.int.goe.de.n0emis.eu:8006"
            insecureSkipVerify: true
