http:
  routers:
    service-gitea-http:
      rule: "Host(`git.n0emis.eu`) || Host(`git.noemis.me`)"
      service: "service-gitea@file"
      entryPoints:
        - "http"
      middlewares:
        - "https_redirect"
    service-gitea-https:
      rule: "Host(`git.n0emis.eu`) || Host(`git.noemis.me`)"
      service: "service-gitea@file"
      entryPoints:
        - "https"
      tls:
        certResolver: "{{ traefik_default_cert_resovler }}"
  services:
    service-gitea:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ gitea_http_port }}"
